10-comfortable: []
10-fired: []
10-handover: []
10-newcomers:
- key: community_of_practice
  term: community of practice
- key: lpp
  term: legitimate peripheral participation
10-persuade:
- key: 90_9_1_rule
  term: 90-9-1 rule
automation:
- key: build_manager
  term: build manager
- key: ci
  term: continuous integration
- key: critical_mass
  term: critical mass
- key: devops
  term: DevOps
- key: json
  term: JavaScript Object Notation
- key: linter
  term: linter
- key: package_manifest
  term: package manifest
- key: pattern_rule
  term: pattern rule
- key: post_commit_hook
  term: post-commit hook
- key: pre_commit_hook
  term: pre-commit hook
- key: static_analysis
  term: static analysis
- key: style_checker
  term: style checker
bibliography: []
business: []
communicate:
- key: discoverability
  term: discoverability
- key: doc_comment
  term: doc comment
- key: docstring
  term: docstring
- key: issue_label
  term: label (an issue)
- key: issue_tracker
  term: issue tracker
- key: mail_filter
  term: mail filter
- key: milestone
  term: milestone
- key: reprex
  term: reproducible example (reprex)
- key: static_site_generator
  term: static site generator
- key: technical_debt
  term: technical debt
- key: utc
  term: Coordinated Universal Time
conclusion: []
conduct: []
conflict:
- key: active_listening
  term: active listening
- key: hitchhiker
  term: hitchiker
contributing: []
debugging:
- key: automated_program_repair
  term: automated program repair
- key: breakpoint
  term: breakpoint
- key: conditional_breakpoint
  term: conditional breakpoint
- key: delta_debugging
  term: delta debugging
- key: failure
  term: failure
- key: fault
  term: fault
- key: rabbit_hole
  term: rabbit hole
- key: requirements_error
  term: requirements error
- key: symbolic_debugger
  term: symbolic debugger
delivery:
- key: semantic_versioning
  term: semantic versioning
- key: version_number
  term: version number
design:
- key: actor
  term: actor
- key: aih
  term: already invented here syndrome
- key: analysis_paralysis
  term: analysis paralysis
- key: base_class
  term: base class
- key: conceptual_architecture
  term: conceptual architecture
- key: derive
  term: derive
- key: design_by_contract
  term: design by contract
- key: er_diagram
  term: entity-relationship diagram
- key: fsm
  term: finite state machine
- key: key
  term: key
- key: layered_configuration
  term: layered configuration
- key: microservice
  term: microservice
- key: nih
  term: not invented here syndrome
- key: open_closed_principle
  term: Open-Closed Principle
- key: post_condition
  term: post-condition
- key: pre_condition
  term: pre-condition
- key: rest
  term: Representational State Transfer
- key: scriptable
  term: scriptable
- key: type_declaration
  term: type declaration
- key: uml
  term: Unified Modeling Language
- key: use_case_map
  term: use-case map
- key: user_story
  term: user story
- key: workflow_diagram
  term: workflow diagram
errors:
- key: assertion
  term: assertion
- key: catch_exception
  term: catch (an exception)
- key: csv
  term: comma-separated values
- key: defensive_programming
  term: defensive programming
- key: exception
  term: exception
- key: external_error
  term: external error
- key: internal_error
  term: internal error
- key: logging
  term: logging
- key: raise_exception
  term: raise (an exception)
- key: rotating_file
  term: rotating file
- key: yaml
  term: YAML
evaluation: []
git-solo:
- key: branch_git
  term: branch
- key: branch_per_feature_workflow
  term: branch-per-feature workflow
- key: centralized_system
  term: centralized system
- key: clone_git
  term: clone
- key: commit
  term: commit
- key: commit_message
  term: commit message
- key: conflict_git
  term: conflict
- key: decentralized_system
  term: decentralized system
- key: flag
  term: flag
- key: mental_model
  term: mental model
- key: merge_git
  term: merge
- key: pull_git
  term: pull
- key: push_git
  term: push
- key: remote_git
  term: remote
- key: repository
  term: repository
- key: software_portal
  term: software portal
- key: sub_command
  term: sub-command
- key: timestamp
  term: timestamp
git-team:
- key: code_review
  term: code review
- key: fork_git
  term: fork
- key: pull_request
  term: pull request
- key: rebase_git
  term: rebase
glossary: []
important:
- key: adhd
  term: attention-deficit/hyperactivity disorder
- key: crunch_mode
  term: crunch mode
- key: decision_meeting
  term: decision meeting
- key: discussion_meeting
  term: discussion meeting
- key: flow
  term: flow
- key: governance
  term: governance
- key: marthas_rules
  term: Martha's Rules
- key: neurodivergent
  term: neurodivergent
- key: neurotypical
  term: neurotypical
- key: sense_vote
  term: sense vote
- key: tone_policing
  term: tone policing
internships:
- key: myers_briggs
  term: Myers-Briggs Type Indicator
- key: ocean_model
  term: OCEAN model
introduction:
- key: preparatory_privilege
  term: preparatory privilege
ip:
- key: bsd_license
  term: BSD license
- key: cc0
  term: CC0
- key: cc_by
  term: CC-BY
- key: copyright
  term: copyright
- key: gpl
  term: GNU Public License
- key: intellectual_property
  term: intellectual property
- key: license
  term: license
- key: mit_license
  term: MIT License
- key: non_disclosure_agreement
  term: non-disclosure agreement
- key: open_license
  term: open license
- key: patent
  term: patent
- key: trade_secret
  term: trade secret
- key: trademark
  term: trademark
license: []
links: []
methods:
- key: confounding_variables
  term: confounding variables
- key: control_group
  term: control group
- key: data_mining
  term: data mining
- key: double_blind
  term: double blind
- key: placebo
  term: placebo
- key: post_mortem
  term: post-mortem
- key: pre_registration
  term: pre-registration
- key: qualitative_method
  term: qualitative method
- key: quasi_experiment
  term: quasi experiment
- key: treatment_group
  term: treatment group
novices: []
process:
- key: ae
  term: analysis & estimation
- key: boehm_curve
  term: Boehm Curve
- key: business_rule
  term: business rule
- key: development_process
  term: development process
- key: feature_boxing
  term: feature boxing
- key: json
  term: JavaScript Object Notation
- key: pair_programming
  term: pair programming
- key: product_manager
  term: product manager
- key: project_manager
  term: project manager
- key: schema
  term: schema
- key: stand_up_meeting
  term: stand-up meeting
- key: tdd
  term: test-driven development
- key: time_boxing
  term: time boxing
- key: triage
  term: triage
- key: waterfall_model
  term: waterfall model
research:
- key: affective_state
  term: affective state
- key: big_five
  term: Big Five personality traits
- key: brooks_law
  term: Brook's Law
- key: code_metric
  term: code metric
- key: cognitive_dimensions
  term: cognitive dimensions framework
- key: dead_code
  term: dead code
- key: dynamic_typing
  term: dynamic typing
- key: fmri
  term: fmri
- key: gqm
  term: goal-question-metric
- key: premature_commitment
  term: premature commitment
- key: root_cause
  term: root cause
- key: static_typing
  term: static typing
rights:
- key: ally
  term: ally
- key: oppression
  term: oppression
- key: privilege
  term: privilege
security:
- key: 2fa
  term: two-factor authentication
- key: casual_threat
  term: casual threat
- key: dictionary_attack
  term: dictionary attack
- key: digital_signature
  term: digital signature
- key: insider_threat
  term: insider threat
- key: intimate_threat
  term: intimate threat
- key: phishing
  term: phishing
- key: security_theater
  term: security theater
- key: social_engineering
  term: social engineering
- key: spearphishing
  term: spearphishing
- key: sql_injection
  term: SQL injection attack
- key: xss
  term: cross-site scripting attack
starting:
- key: elevator_pitch
  term: elevator pitch
- key: feigning_ignorance
  term: feigning ignorance
- key: hr
  term: Human Resources
- key: schrodingers_asshole
  term: "Schr\xF6dinger's Asshole"
teams:
- key: alpha_geek
  term: alpha geek
- key: big_bang
  term: big-bang integration
- key: chaotic_decomposition
  term: chaotic decomposition
- key: feature_creep
  term: feature creep
- key: feature_decomposition
  term: feature decomposition
- key: functional_decomposition
  term: functional decomposition
- key: modular_decomposition
  term: modular decomposition
- key: rotating_decomposition
  term: rotating decomposition
- key: sociotechnical_congruence
  term: sociotechnical congruence
- key: team_contract
  term: team contract
testing:
- key: actual_result
  term: actual result (of test)
- key: code_coverage
  term: code coverage
- key: css_selector
  term: CSS selector
- key: design_for_test
  term: design for test
- key: design_pattern
  term: design pattern
- key: embedded_database
  term: embedded database
- key: expected_result
  term: expected result (of test)
- key: fidelity
  term: fidelity
- key: fixture
  term: fixture
- key: fuzz_testing
  term: fuzz testing
- key: heuristic
  term: heuristic
- key: hot_spot
  term: hot spot
- key: in_memory_database
  term: in-memory database
- key: mock_object
  term: mock object
- key: mvc
  term: model-view-controller
- key: path_coverage
  term: path coverage
- key: profiler
  term: profiler
- key: raster_image
  term: raster image
- key: string_io
  term: string I/O
- key: test_framework
  term: test framework
- key: test_runner
  term: test runner
- key: test_suite
  term: test suite
- key: unit_test
  term: unit test
thinking:
- key: chunking
  term: chunking
- key: cognitive_load
  term: cognitive load
- key: cognitive_transition
  term: cognitive transition
- key: competent_practitioner
  term: competent practitioner
- key: diagnostic_power
  term: diagnostic power
- key: expert
  term: expert
- key: expert_blind_spot
  term: expert blind spot
- key: extraneous_load
  term: extraneous-load
- key: formative_assessment
  term: formative assessment
- key: germane_load
  term: germane load
- key: hypercorrection_effect
  term: hypercorrection_effect
- key: intrinsic_load
  term: intrinsic load
- key: long_term_memory
  term: long-term memory
- key: mental_model
  term: mental model
- key: novice
  term: novice
- key: pck
  term: pedagogical content knowledge
- key: short_term_memory
  term: short-term memory
- key: working_memory
  term: working memory
tooling:
- key: auto_completion
  term: auto-completion
- key: code_browser
  term: code browser
- key: compiled_language
  term: compiled language
- key: console
  term: console
- key: curly_brace_language
  term: curly-brace language
- key: doc_generator
  term: documentation generator
- key: dynamic_analysis
  term: dynamic analysis
- key: dynamic_typing
  term: dynamic typing
- key: experimental_control
  term: experimental control
- key: generational_garbage_collection
  term: generational garbage collection
- key: gui_designer
  term: GUI designer
- key: ide
  term: Integrated Development Environment
- key: interpreted_language
  term: interpreted language
- key: jit
  term: just-in-time compiler
- key: model
  term: model
- key: package_manager
  term: package manager
- key: plugin
  term: plugin
- key: refactoring
  term: refactoring
- key: strong_typing
  term: strong typing
- key: virtual_machine
  term: virtual machine
- key: wysiwyg
  term: What You See Is What You Get
wide-world: []
